name: Build, Test, Publish

on: [push]

jobs:
  ci:
    name: Build, test, publish docs, and publish package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - name: Check out source code
          uses: actions/checkout@v6

        - name: Enable Corepack
          run: corepack enable

        - name: Use Node.js 💻
          uses: actions/setup-node@v6
          with:
            node-version: 24
            cache: yarn

        - name: Install dependencies
          run: yarn install --immutable

        - name: Test on src/ and get test coverage
          run: yarn test:coverage

        - name: Build
          run: yarn build

        - name: Test on build/ to check minification does not break functionality
          run: yarn test:build

        - name: Build docs
          run: yarn docs

        - name: Copy build to docs/build
          run: |
            if [ -d "build" ]; then
              cp -r build docs/build
            fi

        - name: Copy build to docs/media/build
          run: |
            if [ -d "build" ]; then
              mkdir -p docs/media
              cp -r build docs/media/build
            fi

        - name: Copy examples to docs/media/examples
          run: |
            if [ -d "examples" ]; then
              mkdir -p docs/media
              cp -r examples docs/media/examples
            fi

        - name: Deploy docs
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs

        - name: Publish package
          run: yarn pkg-pr-new publish
