name: Build, Test, Publish

on: [push]

jobs:
  test-publish:
    name: Build, test, and publish package
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
        - name: Check out source code
          uses: actions/checkout@v6

        - name: Enable Corepack
          run: corepack enable

        - name: Use Node.js 💻
          uses: actions/setup-node@v6
          with:
            node-version: 24
            cache: yarn

        - name: Install dependencies
          run: yarn install --immutable

        - name: Test and Coverage
          run: yarn test:coverage

        - name: Build
          run: yarn build

        - name: Test on build/
          run: yarn test:build

        - name: Test in browser (If UMD tests are failing, check torch-bridge.js)
          run: |
            yarn serve &
            npx wait-on tcp:8080
            npx mocha-headless-chrome -a no-sandbox -t 60000 -f http://127.0.0.1:8080/test/index.html
            npx mocha-headless-chrome -a no-sandbox -t 60000 -f http://127.0.0.1:8080/test/umd.html

        - name: Build docs and prepare directory
          run: |
            yarn docs
            mkdir -p docs/media
            [ -d "build" ] && cp -r build docs/build
            [ -d "build" ] && cp -r build docs/media/build
            [ -d "examples" ] && cp -r examples docs/examples
            [ -d "examples" ] && cp -r examples docs/media/examples

        - name: Upload Pages Artifact
          uses: actions/upload-pages-artifact@v4
          with:
            path: './docs'

        - name: Publish package
          run: yarn pkg-pr-new publish

  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: test-publish
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
