name: Pyodide Test

on: [push]

jobs:
  pyodide-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn

      - run: yarn install --immutable

      - run: yarn build

      - name: Install Pyodide example dependencies
        run: cd examples/pyodide && yarn install --immutable

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'
          cache-dependency-path: scripts/requirements.txt

      - run: pip install -r scripts/requirements.txt

      - name: Generate PyTorch output
        run: cd examples/pyodide && yarn gen-cache

      - name: Run Pyodide Tests
        run: cd examples/pyodide && yarn test-pyodide
